version: '3.7'
services:
  apache:
    build:
      context: ./apache-dev
    ports:
      - 80:80
    volumes:
    - .:/app
    environment:
      XDEBUG_CONFIG: remote_port=9000
    # important:
    network_mode: 'host'

  cli:
    build:
      context: ./cli-dev
    volumes:
    - .:/app
    environment:
      XDEBUG_CONFIG: remote_port=9090
    command: php loop.php
    # important:
    network_mode: 'host'
